FROM repoweb-microsrv.intra.fazenda.sp.gov.br:5000/dotnet/aspnet:6.0-alpine

#Argumentos passados no Build
ARG user
ARG pass

#Diretorio base da aplicação
WORKDIR /var/api/modelo_core_webapi

#Porta exposta do container
EXPOSE 8080

#Porta que a aplicação funcionará
ENV ASPNETCORE_URLS=http://+:8080
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false

#Adiciona usuario do Container (Non Root)
RUN adduser -D app

#Instala dependencias (Globalization e autenticação Kerberos)
RUN https_proxy=http://proxyservidores.lbintra.fazenda.sp.gov.br:8080 apk add icu-libs krb5

#Copia arquivos da aplicação
COPY . .

#Cria script para autenticação Kerberos e ajusta arquivos de script
RUN echo "echo \"$pass\" |kinit $user@INTRA.FAZENDA.SP.GOV.BR" > klogin.sh &&\
    dos2unix krenew.sh &&\
    dos2unix entrypoint.sh &&\
    chown app *.sh &&\
    chmod +x *.sh 

#Executa entrypoint como Non Root
USER app

#Copia arquivo de configuração para autenticação Kerberos
COPY krb5.conf /etc/krb5.conf

#ENTRYPOINT ["dotnet", "modelo_core_webapi.dll"]
#Script de execução do container
ENTRYPOINT ["sh", "./entrypoint.sh"]