FROM repoweb-microsrv.intra.fazenda.sp.gov.br:5000/dotnet/aspnet:3.1-alpine

#Argumentos passados no Build
ARG user
ARG pass

WORKDIR /var/api/modelo_core_webapi
EXPOSE 8080
EXPOSE 8443

#
ENV ASPNETCORE_URLS=http://+:8080
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false

#Adiciona usuario do Container (Non Root)
RUN adduser -D app

#Instala dependencias (Globalization e autenticação Kerberos)
RUN https_proxy=http://proxyservidores.lbintra.fazenda.sp.gov.br:8080 apk add icu-libs krb5


#Copia arquivos da aplicação
COPY . .

RUN echo "echo \"$pass\" |kinit $user@INTRA.FAZENDA.SP.GOV.BR" > klogin.sh &&\
    dos2unix krenew.sh &&\
    dos2unix entrypoint.sh &&\
    chown app *.sh &&\
    chmod +x *.sh 

#Executa entrypoint como Non Root
USER app

#Copia arquivo de configuração para autenticação Kerberos
COPY krb5.conf /etc/krb5.conf

#Inicia ticket de autenticação Kerberos
#RUN echo "$pass" |kinit $user@INTRA.FAZENDA.SP.GOV.BR && chmod +x *.sh
#ENTRYPOINT ["dotnet", "modelo_core_webapi.dll"]

#Script de execução do container
ENTRYPOINT ["sh", "./entrypoint.sh"]