FROM repoweb-microsrv.intra.fazenda.sp.gov.br:5000/dotnet/aspnet:3.1-alpine
WORKDIR /var/api/modelo_core_webapi
EXPOSE 80
EXPOSE 443
COPY . .
RUN https_proxy=http://proxyservidores.lbintra.fazenda.sp.gov.br:8080 apk add icu-libs
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false
ENTRYPOINT ["dotnet", "modelo_core_webapi.dll"]