FROM repoweb-microsrv.intra.fazenda.sp.gov.br:5000/dotnet/aspnet:3.1-alpine
WORKDIR /var/api/modelo_core_webapi
EXPOSE 80
EXPOSE 443
COPY . .
COPY krb5.conf /etc/krb5.conf
#Inicia ticket de autenticação Kerberos
RUN kinit cs_sitecia_dev -k -t cs_sitecia_dev.keytab
RUN https_proxy=http://proxyservidores.lbintra.fazenda.sp.gov.br:8080 apk add icu-libs krb5
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false
ENTRYPOINT ["dotnet", "modelo_core_webapi.dll"]